### ISSUE TITLE
Migrate to heroku

### ISSUE THREAD

**Issue by mlhamel** [mtlpy/mtlpyweb#31]
**Description**

We want to migrate our website to heroku. 

**TODO**

To do that we needs to:
- [x] Setup a free account on heroku
- [x] Build a empty and working website on heroku 
- [ ] Migrate data from the old website
- [ ] Make the current media working
- [ ] Find a better solution for media in the long term

And then we'll needs
- [ ] Migrate to a full account/organization heroku

**Comment by pior** [comment]
The migration was completed.

- cloudflare (for APEX domain + SSL)
- heroku (for CD)
- MySQL
- database was migrated with a stupid dump/restore operation
- media are on S3 (mtlpy-media bucket)
- old media are on S3
